# NumPy 

NumPy is a powerful linear algebra library for Python. What makes it so important is that almost all of the libraries in the <a href='https://pydata.org/'>PyData</a> ecosystem (pandas, scipy, scikit-learn, etc.) rely on NumPy as one of their main building blocks. Plus we will use it to generate data for our analysis examples later on!

NumPy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy. To get started we need to install it!

NumPy是一个强大的Python线性代数库。 是什么让它如此重要的是，PyData生态系统中的几乎所有库（pandas，scipy，scikit-learn等。）依靠NumPy作为他们的主要构建块之一。 此外，我们将使用它为我们的分析示例生成数据！

NumPy也非常快，因为它与C库绑定。 有关为什么要使用数组而不是列表的更多信息，请查看这个伟大的StackOverflow帖子。

我们只会学习NumPy的基础知识。 要开始，我们需要安装它！

## *Note*: Numpy Installation Instructions  安装说明

_____
##### 

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**

**强烈建议您使用Anaconda发行版安装Python，以确保所有基础依赖项（如线性代数库）都与使用conda安装同步。 如果您有Anaconda，请通过转到终端或命令提示符并键入来安装NumPy:**
    
    conda install numpy
    
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](https://www.scipy.org/install.html)**

**如果您没有Anaconda并且无法安装它，请参阅Numpy的官方文档有关各种安装说明。**

_____

## Importing NumPy

Once you've installed NumPy you can import it as a library:

In [3]:
import numpy as np

NumPy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of NumPy: vectors, arrays, matrices and number generation. Let's start by discussing arrays.

NumPy具有许多内置功能和功能。 我们不会复盖所有这些，而是将重点放在NumPy的一些最重要的方面：向量，数组，矩阵和数字生成。 让我们从讨论数组开始。

# NumPy Arrays

NumPy arrays are the main way we will use NumPy throughout the course. NumPy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-dimensional (1D) arrays and matrices are 2D (but you should note a matrix can still have only one row or one column).

NumPy数组是我们在整个课程中使用NumPy的主要方式。 NumPy数组基本上有两种口味：向量和矩阵。 向量是严格的一维（1D）数组和矩阵是2D（但你应该注意一个矩阵仍然只能有一行或一列）。

## Why use Numpy array? Why not just a list?

There are lot's of reasons to use a Numpy array instead of a "standard" python list object. Our main reasons are:
* Memory Efficiency of Numpy Array vs list
* Easily expands to N-dimensional objects
* Speed of calculations of numpy array
* Broadcasting operations and functions with numpy
* All the data science and machine learning libraries we use are built with Numpy

使用Numpy数组而不是"标准"python列表对象有很多理由。 我们的主要原因是:
* Numpy数组vs列表的内存效率
* 轻松扩展到N维对象
* Numpy数组的计算速度
* 广播操作和功能与numpy
* 我们使用的所有数据科学和机器学习库都是用Numpy构建的

## Simple Example of what numpy array can do

In [2]:
my_list = [1,2,3]
my_array = np.array([1,2,3])

In [3]:
type(my_list)

list

Let's begin our introduction by exploring how to create NumPy arrays.

让我们通过探索如何创建NumPy数组开始我们的介绍。

## Creating NumPy Arrays from Objects

### From a Python List

We can create an array by directly converting a list or list of lists:

我们可以通过直接转换列表或列表列表来创建数组:

In [4]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods to create arrays

There are lots of built-in ways to generate arrays.

有很多内置的方法来生成数组。

### arange

Return evenly spaced values within a given interval. [[参考](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

返回给定间隔内均匀间隔的值。 

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones. [[参考](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

生成零或一的数组。

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace 
Return evenly spaced numbers over a specified interval. [[参考](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

在指定的时间间隔内返回均匀间隔的数字。

In [14]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [15]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

<font color=green>Note that `.linspace()` *includes* the stop value. To obtain an array of common fractions, increase the number of items:</font>

<font color=green>请注意`.linspace()`包括停止值。 要获得一个通分数组，增加项目的数量:</font>

In [16]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

### eye

Creates an identity matrix [[参考](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

创建单位矩阵

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 
Numpy also has lots of ways to create random number arrays:

Numpy也有很多方法来创建随机数数组:

### rand
Creates an array of the given shape and populates it with random samples from a uniform distribution over ``[0, 1)``. [[参考](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

创建一个给定形状的数组，并用均匀分布在`[0,1)`上的随机样本填充它。

In [18]:
np.random.rand(2)

array([0.73724236, 0.75059236])

In [19]:
np.random.rand(5,5)

array([[0.40296004, 0.28444549, 0.91887079, 0.01364321, 0.80345635],
       [0.47515153, 0.37642768, 0.3423592 , 0.07736733, 0.25818923],
       [0.4362318 , 0.44107664, 0.71618029, 0.93116652, 0.51813825],
       [0.46284063, 0.89101547, 0.94116553, 0.33446382, 0.27371153],
       [0.03125118, 0.40445067, 0.3477093 , 0.26256723, 0.7114799 ]])

### randn

Returns a sample (or samples) from the "standard normal" distribution [σ = 1]. Unlike **rand** which is uniform, values closer to zero are more likely to appear. [[参考](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]

从"标准正态"分布[σ=1]返回样本（或样本）。 与均匀的**rand**不同，更接近零的值更有可能出现。

In [20]:
np.random.randn(2)

array([-0.28870927,  1.44587245])

In [21]:
np.random.randn(5,5)

array([[ 0.35372791,  1.36574784, -1.12820687,  1.46890109, -1.17421301],
       [ 0.42861973, -0.09707679, -0.5115294 , -2.87772964,  0.86871266],
       [ 0.43763265, -0.00563699,  0.32192981, -1.58120249,  0.35138796],
       [-0.12970552, -1.35248102,  0.7906536 , -1.3098914 ,  0.45624931],
       [-0.38491273, -0.2568794 , -0.02376884,  1.03213439,  0.41628017]])

### randint
Returns random integers from `low` (inclusive) to `high` (exclusive).  [[参考](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

返回从"低"（含）到"高"（不含）的随机整数。

np.random.randint(1,100)

In [23]:
np.random.randint(1,100,10)

array([70, 97, 15, 64, 41, 41, 82, 41, 55, 73])

### seed
Can be used to set the random state, so that the same "random" results can be reproduced. [[参考](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

可用于设置随机状态，使得相同的"随机"结果可被再现。

In [24]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [25]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## Array Attributes and Methods

Let's discuss some useful attributes and methods for an array:

让我们讨论数组的一些有用的属性和方法:

In [26]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

## Reshape
Returns an array containing the same data with a new shape. [[参考](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

返回包含具有新形状的相同数据的数组。

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

这些是查找最大值或最小值的有用方法。 或者使用argmin或argmax查找它们的索引位置

In [30]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [31]:
ranarr.max()

39

In [32]:
ranarr.argmax()

7

In [33]:
ranarr.min()

2

In [34]:
ranarr.argmin()

9

## Shape

Shape is an attribute that arrays have (not a method):  [[参考](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

Shape是数组具有的属性（不是方法）:

In [35]:
# Vector
arr.shape

(25,)

In [36]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [37]:
arr.reshape(1,25).shape

(1, 25)

In [38]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [39]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array: [[参考](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

也可以抓取数组中对象的数据类型:

In [40]:
arr.dtype

dtype('int32')

In [4]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')

In [7]:
arr3 = np.array([(2,3),(2,2)])
arr3.dtype

dtype('int32')

In [ ]:
e

In [ ]:
# Great Job!